import React, { useEffect, useRef, useState } from 'react';
import * as THREE from 'three';
import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js';
import './viewer.css';
import './viewer-v2.css';

const API = import.meta.env.VITE_BACKEND_URL || 'http://localhost:8000';
const norm = (a) => ((a % 360) + 360) % 360;
const degToRad = (d) => d * Math.PI / 180;

function OneDView({ heading, pitch, cameraRight, cameraUp, cameraForward, cameraPosition, cameraFov, cameraAspect, centroidScreen, sync }) {
  const mount = useRef(null), dataRef = useRef(null), viewRef = useRef({ center: 0, scale: 1 }), dragRef = useRef(null);
  const [axis, setAxis] = useState('x'); const [, redraw] = useState(0);
  useEffect(() => { let dead = false; fetch(`${API}/api/frame`).then(r => r.ok ? r.json() : null).then(d => { if (!dead && d?.points?.length) { dataRef.current = d; redraw(v => v + 1); } }).catch(() => {}); return () => { dead = true; }; }, []);
  useEffect(() => {
    const root = mount.current; if (!root) return;
    const down = e => { if (sync || e.button !== 0) return; dragRef.current = { x: e.clientX, center: viewRef.current.center }; root.setPointerCapture?.(e.pointerId); };
    const move = e => { if (sync || !dragRef.current) return; const width = Math.max(1, root.clientWidth); viewRef.current.center = dragRef.current.center - (e.clientX - dragRef.current.x) / width * (1 / viewRef.current.scale); redraw(v => v + 1); };
    const up = () => { dragRef.current = null; };
    const wheel = e => { if (sync) return; e.preventDefault(); viewRef.current.scale = Math.min(20, Math.max(.15, viewRef.current.scale * Math.exp(-e.deltaY * .0015))); redraw(v => v + 1); };
    root.addEventListener('pointerdown', down); root.addEventListener('pointermove', move); root.addEventListener('pointerup', up); root.addEventListener('pointercancel', up); root.addEventListener('wheel', wheel, { passive: false });
    return () => { root.removeEventListener('pointerdown', down); root.removeEventListener('pointermove', move); root.removeEventListener('pointerup', up); root.removeEventListener('pointercancel', up); root.removeEventListener('wheel', wheel); };
  }, [sync]);
  useEffect(() => { viewRef.current.center = 0; viewRef.current.scale = 1; redraw(v => v + 1); }, [axis]);
  const points = dataRef.current?.points || [];
  const right = new THREE.Vector3(...(cameraRight || [1, 0, 0])).normalize(), up = new THREE.Vector3(...(cameraUp || [0, 1, 0])).normalize(), forward = new THREE.Vector3(...(cameraForward || [0, 0, 1])).normalize(), position = new THREE.Vector3(...(cameraPosition || [0, 0, 0]));
  const fov = degToRad(Number(cameraFov || 48)), aspect = Math.max(.1, Number(cameraAspect || 1)), tanHalf = Math.tan(fov / 2);
  const project = point => { const p = new THREE.Vector3(Number(point[0] || 0), Number(point[1] || 0), Number(point[2] || 0)).sub(position); const depth = p.dot(forward); if (depth <= .001) return null; const sx = p.dot(right) / (depth * tanHalf * aspect), sy = p.dot(up) / (depth * tanHalf); return axis === 'x' ? sx : sy; };
  const projected = points.map(project), visible = projected.filter(v => v !== null), cameraCenter = sync ? 0 : viewRef.current.center, cameraScale = sync ? 1 : viewRef.current.scale;
  const toPercent = v => 50 + (v - cameraCenter) * 50 * cameraScale, centroid = dataRef.current?.centroid;
  const centroidProjected = sync && centroidScreen ? (axis === 'x' ? Number(centroidScreen.x) : Number(centroidScreen.y)) : (Array.isArray(centroid) ? project(centroid) : null);
  const min = visible.length ? Math.min(...visible) : -1, max = visible.length ? Math.max(...visible) : 1, span = Math.max(.001, max - min), label = axis.toUpperCase();
  const centroidStyle = centroidProjected === null || Number.isNaN(centroidProjected) ? undefined : axis === 'x' ? { left: `${50 + centroidProjected * 50}%`, top: '50%' } : { left: '50%', top: `${50 - centroidProjected * 50}%` };
  return <article className="view-card one-d-card"><div className="card-head"><span>1D</span><small>ONE-DIMENSIONAL SPATIAL PROJECTION · {label}-AXIS</small><span className="angle-readout">{String(Math.round(heading)).padStart(3, '0')}°</span></div><div className="one-d-space one-d-interactive" ref={mount}><div className="one-d-space-grid"/><div className={`one-d-axis-line axis-${axis}`}/>{visible.map((v, i) => axis === 'x' ? <i key={i} className="one-d-cloud-dot" style={{ left: `${toPercent(v)}%`, top: '50%' }} /> : <i key={i} className="one-d-cloud-dot" style={{ left: '50%', top: `${100 - toPercent(v)}%` }} />)}{centroidProjected !== null && <i className="one-d-centroid" style={centroidStyle} />}<span className="one-d-sync-indicator">● {sync ? '3D CAMERA SYNC' : 'LOCAL 1D VIEW'} · {Math.round(heading)}° · PITCH {Math.round(pitch || 0)}°</span><span className="one-d-space-axis-label">1D SPACE · {label} · {sync ? 'EXACT 3D SCREEN PROJECTION' : 'PAN + ZOOM'} · SCREEN {label}</span>{!points.length && <span className="one-d-viewport-hint">LOADING BACKEND POINTS…</span>}<span className="one-d-viewport-hint" style={{ bottom: 27 }}>{span.toFixed(2)} m PROJECTED SPAN</span></div><div className="one-d-controls"><span className="one-d-input-label">INPUT · BACKEND POINT CLOUD</span><span className="grow"/><span className="one-d-axis-toggle-label">AXIS</span><button className={axis === 'x' ? 'selected axis-option' : 'axis-option'} type="button" onClick={() => setAxis('x')}>X-AXIS</button><button className={axis === 'y' ? 'selected axis-option' : 'axis-option'} type="button" onClick={() => setAxis('y')}>Y-AXIS</button></div></article>;
}

function makeDegreeSprite(text) { const canvas = document.createElement('canvas'); canvas.width = 220; canvas.height = 84; const ctx = canvas.getContext('2d'); ctx.clearRect(0, 0, 220, 84); ctx.font = 'bold 32px monospace'; ctx.textAlign = 'center'; ctx.textBaseline = 'middle'; ctx.fillStyle = '#b9e9f2'; ctx.fillText(text, 110, 42); const texture = new THREE.CanvasTexture(canvas); texture.minFilter = THREE.LinearFilter; const sprite = new THREE.Sprite(new THREE.SpriteMaterial({ map: texture, transparent: true, depthWrite: false })); sprite.scale.set(1.05, .4, 1); return sprite; }
function add3DRuler(scene, floorY) { const radius = 3.28, group = new THREE.Group(), pts = []; for (let i = 0; i <= 128; i++) { const a = i / 128 * Math.PI * 2; pts.push(new THREE.Vector3(-Math.sin(a) * radius, floorY + .015, Math.cos(a) * radius)); } group.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints(pts), new THREE.LineBasicMaterial({ color: 0x477b88, transparent: true, opacity: .72 }))); for (let d = 0; d <= 360; d += 10) { const a = degToRad(d), major = d % 30 === 0, inner = radius - (major ? .26 : .15), outer = radius + .13; group.add(new THREE.Line(new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(-Math.sin(a) * inner, floorY + .02, Math.cos(a) * inner), new THREE.Vector3(-Math.sin(a) * outer, floorY + .02, Math.cos(a) * outer)]), new THREE.LineBasicMaterial({ color: major ? 0x8fe9f5 : 0x456b75, transparent: true, opacity: major ? .9 : .6 }))); if (major) { const s = makeDegreeSprite(`${d}°`), r = radius + .58; s.position.set(-Math.sin(a) * r, floorY + .07, Math.cos(a) * r); if (d === 360) { s.position.x -= .3; s.position.z += .3; } group.add(s); } } scene.add(group); }
function buildRawCube(raw) { const vertices = raw?.vertices; if (!Array.isArray(vertices) || vertices.length !== 8) return null; const geometry = new THREE.BufferGeometry(); geometry.setAttribute('position', new THREE.BufferAttribute(new Float32Array(vertices.flat().map(Number)), 3)); geometry.setIndex([0, 1, 2, 0, 2, 3, 4, 6, 5, 4, 7, 6, 0, 4, 5, 0, 5, 1, 3, 2, 6, 3, 6, 7, 1, 5, 6, 1, 6, 2, 0, 3, 7, 0, 7, 4]); geometry.computeVertexNormals(); return geometry; }

function ThreeView({ onViewChange, resetRef, rotateRef }) {
  const mount = useRef(null), viewCallback = useRef(onViewChange); viewCallback.current = onViewChange;
  useEffect(() => {
    const root = mount.current; if (!root) return; let dead = false;
    const scene = new THREE.Scene(); scene.background = new THREE.Color(0x05080a); const camera = new THREE.PerspectiveCamera(48, 1, .05, 200); const defaultPosition = new THREE.Vector3(0, 5.5, -7.5), defaultTarget = new THREE.Vector3(0, 0, 0); camera.position.copy(defaultPosition);
    const renderer = new THREE.WebGLRenderer({ antialias: true }); renderer.setPixelRatio(Math.min(window.devicePixelRatio || 1, 2)); renderer.setClearColor(0x05080a, 1); renderer.domElement.style.width = '100%'; renderer.domElement.style.height = '100%'; renderer.domElement.style.display = 'block'; renderer.domElement.style.touchAction = 'none'; root.appendChild(renderer.domElement);
    const floorY = -1.15, floor = new THREE.GridHelper(18, 36, 0x31515c, 0x172a31); floor.position.y = floorY; scene.add(floor); const axes = new THREE.AxesHelper(3.5); axes.position.set(-4, floorY, -4); scene.add(axes); const base = new THREE.Mesh(new THREE.CircleGeometry(2.8, 64), new THREE.MeshBasicMaterial({ color: 0x0c171b, transparent: true, opacity: .75, side: THREE.DoubleSide })); base.rotation.x = -Math.PI / 2; base.position.y = floorY + .002; scene.add(base); add3DRuler(scene, floorY);
    const solidMaterial = new THREE.MeshBasicMaterial({ color: 0x788f98, side: THREE.DoubleSide }), wireMaterial = new THREE.LineBasicMaterial({ color: 0x9bf5ff }), centroidMaterial = new THREE.MeshBasicMaterial({ color: 0x76ff91, depthTest: false, depthWrite: false }), axisMaterial = new THREE.LineBasicMaterial({ color: 0x76ff91, transparent: true, opacity: .8, depthTest: false, depthWrite: false }); let solid = null, wire = null, centroid = null, xAxis = null;
    const renderRaw = (raw, centroidPoint) => { const geometry = buildRawCube(raw); if (!geometry) return; solid = new THREE.Mesh(geometry, solidMaterial); scene.add(solid); wire = new THREE.LineSegments(new THREE.EdgesGeometry(geometry), wireMaterial); wire.scale.setScalar(1.001); scene.add(wire); const p = Array.isArray(centroidPoint) ? centroidPoint.map(Number) : [0, 0, 0]; xAxis = new THREE.Line(new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(-100, p[1] || 0, p[2] || 0), new THREE.Vector3(100, p[1] || 0, p[2] || 0)]), axisMaterial); xAxis.renderOrder = 999; scene.add(xAxis); centroid = new THREE.Mesh(new THREE.SphereGeometry(.17, 24, 24), centroidMaterial); centroid.position.set(p[0] || 0, p[1] || 0, p[2] || 0); centroid.renderOrder = 1000; scene.add(centroid); };
    const controls = new OrbitControls(camera, renderer.domElement); controls.target.copy(defaultTarget); controls.enableDamping = true; controls.dampingFactor = .075; controls.enableRotate = true; controls.enablePan = true; controls.enableZoom = true; controls.rotateSpeed = .9; controls.panSpeed = 1; controls.zoomSpeed = 1; controls.minDistance = 3; controls.maxDistance = 35; controls.minPolarAngle = .12; controls.maxPolarAngle = Math.PI - .12; controls.screenSpacePanning = true; controls.mouseButtons = { LEFT: THREE.MOUSE.ROTATE, MIDDLE: THREE.MOUSE.DOLLY, RIGHT: THREE.MOUSE.PAN }; controls.touches = { ONE: THREE.TOUCH.ROTATE, TWO: THREE.TOUCH.DOLLY_PAN };
    const changed = () => { const o = camera.position.clone().sub(controls.target), h = Math.hypot(o.x, o.z), heading = h > .0001 ? norm(Math.atan2(o.x, o.z) * 180 / Math.PI) : 180, pitch = Math.atan2(o.y, h) * 180 / Math.PI; const right = new THREE.Vector3(1, 0, 0).applyQuaternion(camera.quaternion).normalize(), up = new THREE.Vector3(0, 1, 0).applyQuaternion(camera.quaternion).normalize(), forward = new THREE.Vector3(0, 0, -1).applyQuaternion(camera.quaternion).normalize(); let centroidScreen = null; if (centroid) { const ndc = centroid.position.clone().project(camera); centroidScreen = { x: ndc.x, y: ndc.y, z: ndc.z }; } viewCallback.current(heading, pitch, right.toArray(), up.toArray(), forward.toArray(), camera.position.toArray(), controls.target.toArray(), camera.fov, camera.aspect, centroidScreen); };
    controls.addEventListener('change', changed); controls.update(); controls.saveState(); changed(); const reset3D = () => { controls.reset(); controls.update(); changed(); }; const rotate3D = amount => { const o = camera.position.clone().sub(controls.target), a = degToRad(amount), x = o.x * Math.cos(a) + o.z * Math.sin(a), z = -o.x * Math.sin(a) + o.z * Math.cos(a); camera.position.set(controls.target.x + x, camera.position.y, controls.target.z + z); controls.update(); changed(); }; if (resetRef) resetRef.current = reset3D; if (rotateRef) rotateRef.current = rotate3D;
    const resize = () => { const w = Math.max(1, root.clientWidth), h = Math.max(1, root.clientHeight); renderer.setSize(w, h, false); camera.aspect = w / h; camera.updateProjectionMatrix(); changed(); }; const ro = new ResizeObserver(resize); ro.observe(root); resize(); fetch(`${API}/api/frame`).then(r => r.ok ? r.json() : null).then(d => { if (!dead && d?.input?.vertices) renderRaw(d.input, d.centroid); changed(); }).catch(() => {});
    let af = 0; const loop = () => { if (dead) return; controls.update(); renderer.render(scene, camera); af = requestAnimationFrame(loop); }; loop(); return () => { dead = true; cancelAnimationFrame(af); ro.disconnect(); controls.removeEventListener('change', changed); controls.dispose(); renderer.domElement.remove(); if (solid) solid.geometry.dispose(); if (wire) { wire.geometry.dispose(); wire.material.dispose(); } if (centroid) centroid.geometry.dispose(); if (xAxis) xAxis.geometry.dispose(); base.geometry.dispose(); base.material.dispose(); renderer.dispose(); };
  }, []);
  return <article className="view-card three-card"><div className="card-head"><span>3D</span><small>Backend raw cuboid · centroid · X-axis · orbit · pan · zoom</small></div><div className="three-stage" ref={mount} /><div className="three-tools"><span>LEFT DRAG · ORBIT</span><span>RIGHT DRAG · PAN</span><span>MIDDLE / WHEEL · ZOOM</span><button type="button" onClick={() => resetRef.current?.()}>RESET · 180°</button></div></article>;
}

function TwoDView({ heading, pitch, cameraRight, cameraUp, cameraForward, cameraPosition, cameraFov, cameraAspect, centroidScreen, sync }) {
  const mount = useRef(null), dataRef = useRef(null), viewRef = useRef({ x: 0, y: 0, scale: 1 }), dragRef = useRef(null);
  const [mode, setMode] = useState('points'); const [, redraw] = useState(0);
  useEffect(() => { let dead = false; fetch(`${API}/api/frame`).then(r => r.ok ? r.json() : null).then(d => { if (!dead && d?.points?.length) { dataRef.current = d; redraw(v => v + 1); } }).catch(() => {}); return () => { dead = true; }; }, []);
  useEffect(() => {
    const root = mount.current; if (!root) return;
    const down = e => { if (sync || e.button !== 0) return; dragRef.current = { x: e.clientX, y: e.clientY, view: { ...viewRef.current } }; root.setPointerCapture?.(e.pointerId); };
    const move = e => { if (sync || !dragRef.current) return; const w = Math.max(1, root.clientWidth), h = Math.max(1, root.clientHeight), d = dragRef.current; viewRef.current.x = d.view.x - (e.clientX - d.x) / w * 2 / d.view.scale; viewRef.current.y = d.view.y + (e.clientY - d.y) / h * 2 / d.view.scale; redraw(v => v + 1); };
    const up = () => { dragRef.current = null; };
    const wheel = e => { if (sync) return; e.preventDefault(); viewRef.current.scale = Math.min(20, Math.max(.15, viewRef.current.scale * Math.exp(-e.deltaY * .0015))); redraw(v => v + 1); };
    root.addEventListener('pointerdown', down); root.addEventListener('pointermove', move); root.addEventListener('pointerup', up); root.addEventListener('pointercancel', up); root.addEventListener('wheel', wheel, { passive: false });
    return () => { root.removeEventListener('pointerdown', down); root.removeEventListener('pointermove', move); root.removeEventListener('pointerup', up); root.removeEventListener('pointercancel', up); root.removeEventListener('wheel', wheel); };
  }, [sync]);
  const points = dataRef.current?.points || [];
  const right = new THREE.Vector3(...(cameraRight || [1, 0, 0])).normalize(), up = new THREE.Vector3(...(cameraUp || [0, 1, 0])).normalize(), forward = new THREE.Vector3(...(cameraForward || [0, 0, 1])).normalize(), position = new THREE.Vector3(...(cameraPosition || [0, 0, 0]));
  const fov = degToRad(Number(cameraFov || 48)), aspect = Math.max(.1, Number(cameraAspect || 1)), tanHalf = Math.tan(fov / 2);
  const project = point => { const p = new THREE.Vector3(Number(point[0] || 0), Number(point[1] || 0), Number(point[2] || 0)).sub(position); const depth = p.dot(forward); if (depth <= .001) return null; const x = p.dot(right) / (depth * tanHalf * aspect), y = p.dot(up) / (depth * tanHalf); return { x, y, depth }; };
  const projected = points.map(project), visible = projected.filter(Boolean), local = sync ? { x: 0, y: 0, scale: 1 } : viewRef.current;
  const toLeft = p => 50 + (p.x - local.x) * 50 * local.scale, toTop = p => 50 - (p.y - local.y) * 50 * local.scale;
  const centroid = dataRef.current?.centroid, centroidProjected = sync && centroidScreen ? { x: Number(centroidScreen.x), y: Number(centroidScreen.y), depth: Number(centroidScreen.z) } : (Array.isArray(centroid) ? project(centroid) : null);
  const projectedSpanX = visible.length ? Math.max(...visible.map(p => p.x)) - Math.min(...visible.map(p => p.x)) : 0, projectedSpanY = visible.length ? Math.max(...visible.map(p => p.y)) - Math.min(...visible.map(p => p.y)) : 0;
  const centroidStyle = centroidProjected && Number.isFinite(centroidProjected.x) && Number.isFinite(centroidProjected.y) ? { left: `${50 + centroidProjected.x * 50}%`, top: `${50 - centroidProjected.y * 50}%` } : undefined;
  const title = mode === 'points' ? 'BACKEND POINT CLOUD' : mode === 'rect' ? 'RECTANGLE OVERLAY' : mode === 'square' ? 'SQUARE OVERLAY' : 'CIRCLE OVERLAY';
  return <article className="view-card two-d-card"><div className="card-head"><span>2D</span><small>EXACT 3D SCREEN PROJECTION · X/Y · {title}</small><span className="angle-readout">{String(Math.round(heading)).padStart(3, '0')}°</span></div><div className="two-d-space two-d-interactive" ref={mount}><div className="two-d-grid-lines"/><div className="two-d-azimuth-ruler"><div className="two-d-ruler-ring">{Array.from({ length: 36 }, (_, i) => i * 10).map(d => { const a = degToRad(d), x = 50 + Math.sin(a) * 50, y = 50 - Math.cos(a) * 50; return <span key={d} className={`two-d-ruler-tick ${d % 30 === 0 ? 'major' : ''}`} style={{ left: `${x}%`, top: `${y}%`, transform: `translate(-50%,-50%) rotate(${d}deg)` }} />; })}{Array.from({ length: 12 }, (_, i) => i * 30).map(d => { const a = degToRad(d), x = 50 + Math.sin(a) * 56, y = 50 - Math.cos(a) * 56; return <span key={d} className="two-d-ruler-label" style={{ left: `${x}%`, top: `${y}%`, transform: 'translate(-50%,-50%)' }}>{d}°</span>; })}<span className="two-d-ruler-label two-d-ruler-360">360°</span></div></div><div className="two-d-center"/>{mode === 'points' && visible.map((p, i) => <i key={i} className="two-d-cloud-point" style={{ left: `${toLeft(p)}%`, top: `${toTop(p)}%` }} />)}{mode === 'rect' && <div className="shape-rect"/>}{mode === 'square' && <div className="shape-square"/>}{mode === 'circle' && <div className="shape-circle"/>}{centroidStyle && <i className="two-d-centroid" style={centroidStyle}/>}<div className="two-d-heading" style={{ transform: `translate(-50%,-100%) rotate(${heading}deg)` }}/><span className="two-d-x-label">X</span><span className="two-d-y-label">Y</span><span className="two-d-sync-indicator">● {sync ? '3D CAMERA SYNC' : 'LOCAL 2D VIEW'} · AZ {Math.round(heading)}° · PITCH {Math.round(pitch || 0)}°</span><span className="two-d-space-axis-label">2D SPACE · {sync ? 'EXACT 3D SCREEN PROJECTION' : 'PAN + ZOOM'} · {projectedSpanX.toFixed(2)} × {projectedSpanY.toFixed(2)} SCREEN SPAN</span>{!points.length && <span className="two-d-viewport-hint">LOADING BACKEND POINTS…</span>}</div><div className="two-d-controls"><button className={mode === 'points' ? 'selected' : ''} onClick={() => setMode('points')}>✦ POINTS</button><button className={mode === 'rect' ? 'selected' : ''} onClick={() => setMode('rect')}>RECT</button><button className={mode === 'square' ? 'selected' : ''} onClick={() => setMode('square')}>SQUARE</button><button className={mode === 'circle' ? 'selected' : ''} onClick={() => setMode('circle')}>CIRCLE</button><span className="grow"/><span className="two-d-input-label">INPUT · BACKEND POINT CLOUD</span><span className="auto-toggle"><b/> GRID</span></div></article>;
}

function TwoFiveDView({ heading }) { const grid = useRef(null); useEffect(() => { if (grid.current) grid.current.style.transform = `rotate(${heading}deg)`; }, [heading]); return <article className="view-card two-five-card"><div className="card-head"><span>2.5D</span><small>Reserved · backend range grid · 360° ruler</small></div><div className="grid-wrap"><div className="grid-surface" ref={grid}><div className="grid-floor"/>{Array.from({ length: 9 }, (_, i) => <div className="scan-row" key={i} style={{ top: `${10 + i * 10}%` }}/>) }{Array.from({ length: 11 }, (_, i) => <div className="scan-col" key={i} style={{ left: `${5 + i * 9}%` }}/>) }<div className="fov-ring ring-a"/><div className="fov-ring ring-b"/><div className="fov-ring ring-c"/><div className="object"/><div className="ego"/></div><div className="ruler">{[0, 30, 60, 90, 120, 150, 180, 210, 240, 270, 300, 330, 360].map(d => <span key={d} style={{ '--pos': `${d / 3.6}` }}>{d}°</span>)}<div className="ruler-pointer" style={{ '--pointer': `${heading / 3.6}%` }}/></div></div><div className="two-five-controls"><span>PAN · ROTATE · MEASURE</span><span className="grow"/><span>2.5D NEXT STAGE</span></div></article>; }

export default function ViewerV2() {
  const [threeHeading, setThreeHeading] = useState(180), [threePitch, setThreePitch] = useState(28), [heading, setHeading] = useState(180), [pitch, setPitch] = useState(28);
  const [cameraRight, setCameraRight] = useState([1, 0, 0]), [cameraUp, setCameraUp] = useState([0, 1, 0]), [cameraForward, setCameraForward] = useState([0, 0, 1]), [cameraPosition, setCameraPosition] = useState([0, 5.5, -7.5]), [cameraTarget, setCameraTarget] = useState([0, 0, 0]), [centroidScreen, setCentroidScreen] = useState({ x: 0, y: 0, z: 0 });
  const [cameraFov, setCameraFov] = useState(48), [cameraAspect, setCameraAspect] = useState(1), [sync, setSync] = useState(true);
  const socket = useRef(null), threeResetRef = useRef(null), threeRotateRef = useRef(null);
  const publish = (h, p, right, up, forward, position, target, fov, aspect, centroidScreenValue) => { if (!sync || socket.current?.readyState !== WebSocket.OPEN) return; socket.current.send(JSON.stringify({ type: 'view_state', heading: norm(h), pitch: Number(p), right, up, forward, position, target, fov: Number(fov), aspect: Number(aspect), centroid_screen: centroidScreenValue || { x: 0, y: 0, z: 0 } })); };
  useEffect(() => { const ws = new WebSocket(API.replace(/^http/, 'ws') + '/ws/view'); socket.current = ws; ws.onmessage = e => { try { const m = JSON.parse(e.data); if (!sync) return; if (typeof m.heading === 'number') setHeading(norm(m.heading)); if (typeof m.pitch === 'number') setPitch(m.pitch); if (Array.isArray(m.right)) setCameraRight(m.right); if (Array.isArray(m.up)) setCameraUp(m.up); if (Array.isArray(m.forward)) setCameraForward(m.forward); if (Array.isArray(m.position)) setCameraPosition(m.position); if (Array.isArray(m.target)) setCameraTarget(m.target); if (typeof m.fov === 'number') setCameraFov(m.fov); if (typeof m.aspect === 'number') setCameraAspect(m.aspect); if (m.centroid_screen && typeof m.centroid_screen.x === 'number') setCentroidScreen(m.centroid_screen); } catch {} }; return () => { ws.close(); socket.current = null; }; }, [sync]);
  const handleThreeView = (h, p, right, up, forward, position, target, fov, aspect, centroidScreenValue) => { const hv = norm(h), pv = Number(p), rr = right || [1, 0, 0], uu = up || [0, 1, 0], ff = forward || [0, 0, 1], pp = position || [0, 5.5, -7.5], tt = target || [0, 0, 0], fv = Number(fov || 48), ar = Number(aspect || 1), cs = centroidScreenValue || { x: 0, y: 0, z: 0 }; setThreeHeading(hv); setThreePitch(pv); setCameraRight(rr); setCameraUp(uu); setCameraForward(ff); setCameraPosition(pp); setCameraTarget(tt); setCameraFov(fv); setCameraAspect(ar); setCentroidScreen(cs); if (sync) { setHeading(hv); setPitch(pv); publish(hv, pv, rr, uu, ff, pp, tt, fv, ar, cs); } };
  const toggleSync = () => setSync(enabled => { const next = !enabled; if (next) { setHeading(threeHeading); setPitch(threePitch); window.setTimeout(() => { if (socket.current?.readyState === WebSocket.OPEN) socket.current.send(JSON.stringify({ type: 'view_state', heading: norm(threeHeading), pitch: Number(threePitch), right: cameraRight, up: cameraUp, forward: cameraForward, position: cameraPosition, target: cameraTarget, fov: cameraFov, aspect: cameraAspect, centroid_screen: centroidScreen })); }, 0); } return next; });
  const rotateBy = v => threeRotateRef.current ? threeRotateRef.current(v) : handleThreeView(threeHeading + v, threePitch, cameraRight, cameraUp, cameraForward, cameraPosition, cameraTarget, cameraFov, cameraAspect, centroidScreen);
  const resetAll = () => threeResetRef.current ? threeResetRef.current() : handleThreeView(180, 28, [1, 0, 0], [0, 1, 0], [0, 0, 1], [0, 5.5, -7.5], [0, 0, 0], 48, cameraAspect, centroidScreen);
  return <main className="app-shell"><header className="hero"><div><h1>Foveated LiDAR Mapping</h1><p>3D model · 1D profile · 2D projection · 2.5D range map</p></div><div className="hero-meta"><b>● 3D RESET · 180° DEFAULT</b><small>0° TOP · 90° RIGHT · 180° BOTTOM · 270° LEFT</small></div></header><section className="toolbar"><span className="badge">4 SPACES</span><span className="badge">3D → 1D → 2D → 2.5D</span><span className="grow"/><button className={`sync-button ${sync ? 'sync-active' : 'sync-off'}`} type="button" onClick={toggleSync}>• SYNC {sync ? 'ON' : 'OFF'}</button><button type="button" onClick={() => rotateBy(-5)}>↶ 5°</button><button type="button" onClick={() => rotateBy(5)}>5° ↷</button><button type="button" onClick={resetAll}>RESET · 180°</button></section><section className="view-grid"><ThreeView onViewChange={handleThreeView} resetRef={threeResetRef} rotateRef={threeRotateRef}/><OneDView heading={heading} pitch={pitch} cameraRight={cameraRight} cameraUp={cameraUp} cameraForward={cameraForward} cameraPosition={cameraPosition} cameraFov={cameraFov} cameraAspect={cameraAspect} centroidScreen={centroidScreen} sync={sync}/><TwoDView heading={heading} pitch={pitch} cameraRight={cameraRight} cameraUp={cameraUp} cameraForward={cameraForward} cameraPosition={cameraPosition} cameraFov={cameraFov} cameraAspect={cameraAspect} centroidScreen={centroidScreen} sync={sync}/><TwoFiveDView heading={heading}/></section><section className="analysis panel"><div><span className="section-kicker">FOV / ORIENTATION</span><strong>{Math.round(threeHeading)}° / {Math.round(threePitch)}°</strong><small>{sync ? 'linked 3D camera' : '3D camera · sync paused'}</small></div><div><span className="section-kicker">INPUT</span><strong>RAW CUBOID</strong><small>backend/data/raw/cube.json</small></div><div><span className="section-kicker">CENTROID</span><strong>BACKEND COMPUTED</strong><small>geometric center of raw vertices · Y = 0</small></div></section></main>;
}
